spring.application.name=demo
server.port=8090

# Clave para firmar JWT (Configuración del Laboratorio)
app.jwt.secret=EsteEsUnSecretoMuyLargoParaFirmarTokensJwtDeLaboratorio1234567890
app.jwt.expiration-minutes=60

# Conexión a la base de datos de XAMPP
spring.datasource.url=jdbc:mysql://localhost:3306/torneos_db
spring.datasource.username=root
spring.datasource.password=

# Configuración de Hibernate para que cree las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

